"""Render nudl's icon to a multi-resolution .ico. Build-time only.

This is the ONLY place Pillow is used by the shipped product, and it lives outside
`src/` on purpose. PyInstaller bundles what it can reach by walking imports from
`run_nudl.py`; keeping the renderer out of that graph is what stops 12.8 MB of image
codecs — a 7.5 MB AVIF decoder among them — from riding along to draw four shapes.

At runtime `tray.py` loads the .ico this produces. Rendering once per build also gives
Windows the seven discrete sizes below to choose from, instead of one 64px image it has
to downsample to 16px for the tray.

Usage:  python tools/make_icon.py [output.ico]
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw

#: Written here when no output path is given. Committed, so a source checkout runs
#: without a build step, and regenerated by build.ps1 so it cannot drift from this code.
DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / "src" / "nudl.ico"

#: Windows picks the closest of these for the tray, the taskbar, and Explorer.
SIZES = (16, 24, 32, 48, 64, 128, 256)

_BG = (22, 24, 29, 255)
_ACCENT = (76, 183, 130, 255)


def icon_image(size: int = 64) -> Image.Image:
    """A green 'n' on a dark rounded tile — legible at 16px in the tray."""
    image = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    draw = ImageDraw.Draw(image)
    draw.rounded_rectangle((0, 0, size - 1, size - 1), radius=size // 5, fill=_BG)

    # Draw the 'n' as strokes rather than text: font availability varies by machine,
    # and a missing glyph would leave an empty tray icon.
    weight = max(3, size // 10)
    left, right = size // 4, size - size // 4
    top, bottom = size // 3, size - size // 4
    draw.line((left, top, left, bottom), fill=_ACCENT, width=weight)
    draw.line((right, top + weight, right, bottom), fill=_ACCENT, width=weight)
    draw.arc(
        (left, top - weight, right, top + (bottom - top) // 2),
        start=180,
        end=360,
        fill=_ACCENT,
        width=weight,
    )
    return image


def write_ico(destination: Path) -> Path:
    destination.parent.mkdir(parents=True, exist_ok=True)
    icon_image(max(SIZES)).save(destination, sizes=[(s, s) for s in SIZES])
    return destination


def main(argv: list[str]) -> int:
    destination = Path(argv[1]) if len(argv) > 1 else DEFAULT_OUTPUT
    written = write_ico(destination)
    print(f"  {written} ({written.stat().st_size:,} bytes, {len(SIZES)} sizes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
