"""Generate docs/RULES.md from src/rules.json.

Written by a script, not by hand, so the published list can never drift away from what
nudl actually does. Run it after editing rules.json:

    python docs/make_rules_doc.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RULES = json.loads((ROOT / "src" / "rules.json").read_text(encoding="utf-8"))
OUT = ROOT / "docs" / "RULES.md"

# The "deliberately absent" notes live in rules.json's $comment block, but they are the
# most important thing on this page, so they are restated here as structured data.
NEVER_STRIPPED = [
    (
        "si",
        "Spotify",
        "Share id. Removing it has broken shared-playlist flows. "
        "(YouTube's `si` is only a tracker, and is stripped.)",
    ),
    ("sk", "Medium", "**Friend-link token.** Strip it and you paywall the article."),
    ("hash", "eBay", "Identifies the item. Only the `_trk*` params there are tracking."),
    ("img_index", "Instagram", "Which photo in the carousel."),
    ("sid", "Booking.com", "Session id."),
    ("context", "Reddit", "How many parent comments to show."),
    ("keywords", "Amazon", "On `/s?keywords=` this **is** the search query."),
    ("check_in / check_out", "Airbnb", "The actual booking dates."),
    ("v / t / list / index", "YouTube", "Video, timestamp, playlist, position."),
    ("q / page / id", "everywhere", "Never on the list. Unknown keys are always kept."),
]


def fmt(keys: list[str]) -> str:
    return " ".join(f"`{k}`" for k in keys)


lines: list[str] = []
add = lines.append

add("# What nudl removes")
add("")
add("<!-- Generated by docs/make_rules_doc.py from src/rules.json. Do not edit by hand. -->")
add("")
add("nudl strips **only** the keys on this page. Every other query parameter — including")
add("ones nobody has thought of yet — is left untouched. That is what keeps it from")
add("breaking links.")
add("")
add("Matching is on the parameter **key**, case-insensitively, and never on its value.")
add("")

add("## Removed everywhere")
add("")
add("These ride along to whatever site you land on, so they are stripped on every host.")
add("")
add(fmt(RULES["global_tracker_keys"]))
add("")
add("`^utm_.*$` is an anchored regex: it matches `utm_source`, `utm_medium`, `utm_campaign`,")
add("`utm_term`, `utm_content` and any other `utm_` key, but **not** `utm` used as a value.")
add("")

add("## Removed on specific sites")
add("")
add("| Site | Parameters removed |")
add("| --- | --- |")
for provider in RULES["providers"]:
    name = provider["name"]
    keys = provider.get("rules", [])
    if keys:
        add(f"| **{name}** | {fmt(keys)} |")
add("")

add("## Redirect wrappers unwrapped")
add("")
add("nudl pulls the real destination out of these and throws the wrapper away. It does this")
add("**locally**, by decoding the parameter — never by following the link.")
add("")
add("| Wrapper | Target parameter |")
add("| --- | --- |")
for wrapper in RULES["redirect_wrappers"]:
    path = wrapper.get("path", "/")
    location = f"`{wrapper['host']}{path if path != '/' else ''}`"
    add(f"| {location} | `{wrapper['param']}` |")
add("")

add("## Never stripped — on purpose")
add("")
add("These **look** like trackers. Removing them breaks the link, so nudl leaves them alone.")
add("Each has a test in `src/tests/test_clean.py` so nobody helpfully adds them later.")
add("")
add("| Parameter | Site | Why it stays |")
add("| --- | --- | --- |")
for key, site, why in NEVER_STRIPPED:
    add(f"| `{key}` | {site} | {why} |")
add("")

add("## Also never touched")
add("")
add("- **Signed URLs.** Any query containing `sig`, `signature`, `hmac`, `token`, `expires`,")
add("  `policy`, or an `X-Amz-*` / `X-Goog-*` / `X-Ms-*` key is returned **completely**")
add("  unchanged. Signed URLs sign the whole query — removing any parameter turns the link")
add("  into a 403.")
add("- **Referral parameters** (" + fmt(RULES.get("referral", [])) + ") are off by default.")
add("  Turn them on with `strip_referral` in `config.json`.")
add("- **Shorteners** (`bit.ly`, `t.co`, …). Expanding them would mean a network request,")
add("  which would leak the link and can burn one-time URLs. Returned unchanged.")
add("")

counts = {
    "global": len(RULES["global_tracker_keys"]),
    "providers": len(RULES["providers"]),
    "provider_keys": sum(len(p.get("rules", [])) for p in RULES["providers"]),
    "wrappers": len(RULES["redirect_wrappers"]),
}
add(
    f"---\n\n{counts['global']} global keys · "
    f"{counts['provider_keys']} site-specific keys across {counts['providers']} sites · "
    f"{counts['wrappers']} redirect wrappers."
)
add("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT}")
print(
    f"  {counts['global']} global, {counts['provider_keys']} provider keys "
    f"({counts['providers']} sites), {counts['wrappers']} wrappers"
)
